apiVersion: v1
kind: Service
metadata:
  name: monolith-to-microservices-feed
  labels:
    app: monolith-to-microservices-feed
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: monolith-to-microservices-feed